
## This is a SAMPLE metadata file for a GitHub Action.  For more info:
##    https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: markdown-reporter
author: Pavan Mudigonda
description: |
  Publishes the markdown file provided in GitHub Actions as Checkrun.

inputs:

  markdown_path:
    description: |
      markdown file path
    required: true

  report_name:
    description: |
      markdown file path
    required: true

  report_title:
    description: |
      markdown file path
    required: true

  github_token:
    description: |
      GITHUB_TOKEN to authenticate against API calls to attach
      report to Workflow Run.
    required: false
    
  skip_check_run:
    description: |
      If true, will skip attaching the Tests Result report to
      the Workflow Run using a Check Run.  Useful if you want to turn if you run in to 65k problem.
    required: false

branding:
  color: purple
  icon: check-circle

## Even though the Action logic may be implemented
## in PWSH, we still need a NodeJS entry point
runs:
  using: node12
  main: _init/index.js
